services:
  # Backend service (Django)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "9000:9000"

  # Frontend service (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
